config/routes.rb
Rails.application.routes.draw do
  get 'abouts/show'

  root 'comments#index'
  resources :comments, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  def self.all_text
    all.order(:id).map { |comment| comment.text }.join
  end

  def self.all_text_json
    { "text" => all_text }.to_json
  end

  def self.filter(args = {})
    results = nil
    args.each do |attribute, values|
      attribute_results = nil
      unless values.nil? || values.include?("all")
        values.each do |value|
          if attribute_results
            attribute_results = where("#{attribute} = ?", "#{value}").or(attribute_results)
          else
            attribute_results = where("#{attribute} = ?", "#{value}")
          end
        end
      end
      if results && attribute_results
        results = results.merge(attribute_results)
      else
        results = attribute_results
      end
    end  
    results || all
  end
end

app/models/keyword_agent.rb
class KeywordAgent
  include HTTParty

  BASE_URI = "https://gateway-a.watsonplatform.net/calls/text/TextGetRankedKeywords"


  def keywords_for(text)
    response = self.class.post(BASE_URI, 
                              body: { apikey: ENV['alchemy_key'],
                                      text: text,
                                      outputMode: 'json',
                                      maxRetrieve: "10" },
                              headers: { "Accept-Encoding" => "" })
    KeywordResponse.new(JSON.parse(response.body))
  end
end

app/models/keyword_response.rb
class KeywordResponse
  attr_reader :words 
  
  def initialize(response_body)
    @response_body = response_body
    @words = {}
    unless response_body['status'] == "ERROR"
      set_words
    end
  end

  def set_words
    @response_body['keywords'].each do |word|
      @words[word['text']] = word['relevance']
    end
  end
end

app/models/tone_agent.rb
class ToneAgent
  include HTTParty

  BASE_URI = "https://gateway.watsonplatform.net/tone-analyzer/api/v3/tone?version=2016-05-19"


  def scores_for(json)
    response = self.class.post(BASE_URI, 
                               body: json,
                               sentences: false,
                               headers: { "Content-Type" => "application/json" },
                               basic_auth: { username: ENV['tone_username'],   
                                             password: ENV['tone_password'] })
    ToneResponse.new(JSON.parse(response.body))
  end
end

app/models/tone_response.rb
class ToneResponse
  attr_reader :emotional_tone, 
              :language_tone, 
              :social_tone

  def initialize(response_body)
    @response_body = response_body
    if response_body['error']
      set_empty_hashes
    else
      set_tone_hashes
    end
  end

  private

  def set_empty_hashes
    @emotional_tone = {}
    @language_tone  = {}
    @social_tone    = {}
  end

  def set_tone_hashes
    set_emotional_tone
    set_language_tone
    set_social_tone
  end

  def set_emotional_tone
    @emotional_tone = {
      anger:   score_at(0,0),
      disgust: score_at(0,1),
      fear:    score_at(0,2),
      joy:     score_at(0,3),
      sadness: score_at(0,4)
    }
  end

  def set_language_tone
    @language_tone = {
      analytical: score_at(1,0),
      confident:  score_at(1,1),
      tentative:  score_at(1,2)
    }
  end

  def set_social_tone
    @social_tone = {
      openness:          score_at(2,0),
      conscientiousness: score_at(2,1),
      extraversion:      score_at(2,2),
      agreeableness:     score_at(2,3),
      emotional_range:   score_at(2,4)   
    }
  end

  def score_at(category_index, tone_index)
    @response_body['document_tone']['tone_categories'][category_index]['tones'][tone_index]['score']
  end
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @selected_categories = params[:categories] ? params[:categories] : []
    @selected_themes     = params[:themes] ? params[:themes] : []
    @comments   = Comment.filter(category: @selected_categories, theme: @selected_themes)
    @categories = CATEGORIES
    @themes     = THEMES
    @scores     = get_scores
    @keywords   = get_keywords
  end

  private

  def get_scores
    ToneAgent.new.scores_for(comments_text_json)
  end

  def comments_text_json
    { "text" => comments_text }.to_json
  end

  def comments_text
    @comments.map { |comment| comment.text }.join
  end

  def get_keywords
    KeywordAgent.new.keywords_for(comments_text)
  end

  CATEGORIES = [ "Personal Experience", "Resources",
                 "Wisdom", "Ideas I Bring", "What's Missing",
                "Why Am I here?", "One Thing To Improve" ]

  THEMES = [ "Jobs, Employment and Training", "Education", "Food Access", 
             "Business", "Justice and Law Enforcement", "Family Support",
             "Housing and Affordability" ]
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/abouts/show.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="row">
    <div class="header">
      <h1>East Austin Zeitgeist</h1>
      <h4><%= link_to "Home", :root %> | About</h4>
    </div>
  </div>
  <div class="jumbotron">
    <h2>What's going on here?</h2>
    <p>I'm glad you asked.</p>
    <p>East Austin Zeitgeist comes from the union of <%= link_to "The Spirit of East Austin", "https://spiritofeastaustin.bloomfire.com/" %> project, and the language processing capabilities of <%= link_to "IBM's artificial intelligence, Watson", "https://www.ibm.com/watson/" %>.</p>
    <p>The Spirit of East Austin exists to co-create a more equitable prosperity in East Austin, by  focused engagement with the community.</p>
    <p>Thousands of comments have been collected from East Austinites, dealing with a variety of themes and categories. East Austin Zeitgeist lets you filter through these comments, and see what Watson makes of them.</p>
  </div>
</div>

app/views/comments/_category_filter.html.erb
<h5>Filter by category<h5>
<div class='checkbox'>
<%= label_tag :all_categories do %>
  <%= check_box_tag 'categories[]', "all", @selected_categories.include?("all"), id: 'all_categories' %>
  All Categories
<% end %>
</div>
<% @categories.each do |category| %>
  <div class="checkbox">
  <%= label_tag category.gsub(" ", "_").gsub("'","").gsub("?", "") do %>
    <%= check_box_tag 'categories[]', category, @selected_categories.include?(category), id: category.gsub(" ", "_").gsub("'","").gsub("?", "") %>
    <%= category %>
  <% end %>
  </div>
<% end %>

app/views/comments/_comment.html.erb
<div class="well">
  <span class="label label-primary"><%=  comment.category %></span>
  <span class="label label-success"><%=  comment.theme %></span>
  <br>
  <br>
  <%= comment.text %>
</div>

app/views/comments/_filter_form.html.erb
<%= form_tag comments_path, method: :get do %>
  <div class="row">
    <div class="col-md-6">
      <%= render 'category_filter' %>
    </div>
    <div class="col-md-6">
      <%= render 'theme_filter' %>
    </div>
  </div>
  <div class="filter-button-container">
    <%= submit_tag "Filter", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/comments/_theme_filter.html.erb
<h5>Filter by theme<h5>
<div class='checkbox'>
<%= label_tag :all_themes do %>
  <%= check_box_tag 'themes[]', "all", @selected_themes.include?("all"), id: 'all_themes' %>
  All Themes
<% end %>
</div>
<% @themes.each do |theme| %>
  <div class="checkbox">
  <%= label_tag theme.gsub(" ", "_").gsub(",","") do %>
    <%= check_box_tag 'themes[]', theme, @selected_themes.include?(theme), id: theme.gsub(" ", "_").gsub(",","") %>
    <%= theme %>
  <% end %>
  </div>
<% end %>

app/views/comments/index.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="row">
    <div class="header">
      <h1>East Austin Zeitgeist</h1>
      <h4>Home | <%= link_to "About", abouts_show_path %></h4>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= render 'filter_form' %>
    </div>
    <div class="col-md-6">
      <h4>Emotial Tone</h4>
      <%= column_chart @scores.emotional_tone %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= pie_chart @comments.group(:category).count %>
    </div>
    <div class="col-md-6">
      <h4>Language Tone</h4>
      <%= column_chart @scores.language_tone %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= pie_chart @comments.group(:theme).count %>
    </div>
    <div class="col-md-6">
      <h4>Social Tone</h4>
      <%= column_chart @scores.social_tone %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= bar_chart @keywords.words %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h4>Sample of comments</h4>
      <%= render @comments.limit(10)%>
    </div>
  </div>
</div>

app/views/comments/show.html.erb
<%= @response %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>East Austin Zeitgeist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>